# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 814ab577aaacf20f9d1c81bf0d53ffdafdf6534a70b067fa168e376e845d2738e4140eda5db0b2c1c2a76ca49685d72ed54de3f9bac42f9ed0e4d84fca2a5042

test:
  secret_key_base: eb2459d0f9e85d743843e60a6b86dc5a47558f3cf0baf7bb073dca6be5e3a94c174a3dbbc9aaf7a3f449cdba441c612e5fc55f6822ba997788368f26604725e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
